booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('',views.IndexListView.as_view(), name='index'),
    path('<int:pk>/calendar/',views.StudioCalendar.as_view(),name='calendar'),
    path('<int:pk>/calendar/<int:year>/<int:month>/<int:day>/',views.StudioCalendar.as_view(),name='calendar'),
    path('<int:pk>/booking/<int:year>/<int:month>/<int:day>/<str:hour>/',views.Booking,name='booking'),
    path('<int:pk>/confirm/<int:personCount>/<str:start_str>/<str:end_str>/',views.Confirm,name='confirm'),

    path('staff/<int:pk>/calendar/',views.StaffStudioCalendar.as_view(), name='staffcalendar'),
    path('staff/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/',views.StaffStudioCalendar.as_view(),name='staffcalendar'),
    path('staff/<int:pk>/detail/<int:year>/<int:month>/<int:day>/',views.Detail.as_view(),name='detail'),
]

bookingapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('booking.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

booking/models.py
from django.db import models
import sys
sys.path.append('../')
from accounts.models import User

# Create your models here.

class Studio(models.Model):
    name = models.CharField('スタジオ名',max_length=255)

    def __str__(self):
        return self.name

class Schedule(models.Model):
    start = models.DateTimeField('開始時間')
    end = models.DateTimeField('終了時間')
    personCount = models.IntegerField('人数')
    user = models.ForeignKey(User,verbose_name="予約者",on_delete=models.CASCADE)
    studio = models.ForeignKey(Studio,verbose_name="スタジオ",on_delete=models.CASCADE)
    created_at = models.DateTimeField("予約完了日時",auto_now_add=True)
    updated_at = models.DateTimeField("変更日時",auto_now=True)

booking/forms.py
from django import forms
from .models import Schedule
from bootstrap_datepicker_plus.widgets import DateTimePickerInput

# class ScheduleForm(forms.ModelForm):
#     class Meta:
#         model = Schedule
#         fields = ('start','end','personCount')
#         labels = {'start':'開始時間','end':'終了時刻','personCount':'ご利用人数'}
#         widgets = {
#             'start': DateTimePickerInput(options={"format": "YYYY/MM/DD HH:00"}),
#             'end': DateTimePickerInput(options={"format": "YYYY/MM/DD HH:00"})
#         }

booking/views.py
import datetime
from django.conf import settings
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Studio, Schedule
import sys
sys.path.append('../')
from accounts.models import User

class IndexListView(generic.ListView):
    template_name = 'booking/index.html'
    model = Studio

class StudioCalendar(generic.TemplateView):
    template_name = 'booking/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        studio = get_object_or_404(Studio, pk=self.kwargs['pk'])
        today = datetime.date.today()

        # どの日を基準にカレンダーを表示するかの処理。
        # 年月日の指定があればそれを、なければ今日からの表示。
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if year and month and day:
            base_date = datetime.date(year=year, month=month, day=day)
        else:
            base_date = today

        # カレンダーは1週間分表示するので、基準日から1週間の日付を作成しておく
        days = [base_date + datetime.timedelta(days=day) for day in range(7)]
        start_day = days[0]
        end_day = days[-1]

        # 9:00~26:00、1週間分の、値がTrueなカレンダーを作る
        # "9:00"~"23:30","0:00"~"1:30"の配列
        time = []
        for i in range(9, 24):
            for j in range(0, 60, 30):
                hour = str(i).zfill(2)
                minute = str(j).zfill(2)
                time.append(hour + ":" + minute)
        for i in range(2):
            for j in range(0, 60, 30):
                hour = str(i).zfill(2)
                minute = str(j).zfill(2)
                time.append(hour + ":" + minute)

        #カレンダーの配列
        calendar = {}
        for count in range(34):
            row = {}
            for day in days:
                row[day] = True
            calendar[time[count]] = row
        
        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(start_day, datetime.time(hour=9, minute=0, second=0))
        end_time = datetime.datetime.combine(end_day+datetime.timedelta(days=1), datetime.time(hour=2, minute=0, second=0))
        for schedule in Schedule.objects.filter(studio=studio).exclude(Q(start__gt=end_time) | Q(end__lt=start_time)):
            start_dt = timezone.localtime(schedule.start)
            end_dt = timezone.localtime(schedule.end)
            booking_start_hour = start_dt.hour
            booking_date = start_dt.date()
            if booking_start_hour <= 2:
                booking_date -= datetime.timedelta(days=1)

            num_start_hour = time.index(start_dt.time().strftime("%H:%M"))
            num_end_hour = time.index(end_dt.time().strftime("%H:%M")) 
            for num in range(num_start_hour,num_end_hour):
                if time[num] in calendar and booking_date in calendar[time[num]]:
                    calendar[time[num]][booking_date] = False
                
        context['studio'] = studio
        context['calendar'] = calendar
        context['days'] = days
        context['start_day'] = start_day
        context['end_day'] = end_day
        context['before'] = days[0] - datetime.timedelta(days=7)
        context['next'] = days[-1] + datetime.timedelta(days=1)
        context['today'] = today
        return context      

@login_required
def Booking(request,pk,year,month,day,hour):
    studio = get_object_or_404(Studio, pk=pk)
    user = get_object_or_404(User, pk=request.user.id)
    # 予約の開始時刻が0:00~1:30であれば日付を+1する
    if hour == ("00:00" or "00:30" or "01:00" or "01:30"):
        day += 1

    # 開始時刻をdatetime型で取得
    start = datetime.datetime.strptime(hour,'%H:%M').replace(year=year,month=month,day=day)
    # 終了時刻の初期値は基本1時間後(もし予約開始が01:30なら最終時刻の02:00が終了時刻)
    if hour == "01:30":
        end = start + datetime.timedelta(minutes=30)
    else:
        end = start + datetime.timedelta(hours=1)
    start_str = start.strftime('%Y%m%d %H:%M')
    end_str = end.strftime('%Y%m%d %H:%M')
    
    context = {'studio': studio,
                'user' : user,
                'start': start_str,
                'end'  : end_str,}

    if request.method == 'POST':
        start_time = datetime.datetime.strptime(request.POST['start'],'%Y/%m/%d %H:%M')
        end_time = datetime.datetime.strptime(request.POST['end'],'%Y/%m/%d %H:%M')

        # if Schedule.objects.filter(studio=studio).exclude(Q(start__gte=end_time) | Q(end__lte=start_time)).exists():
        #     messages.error(request, 'すでに予約が入っています。別の日時をお選びください')
        # else:
        #     object = Schedule.objects.create(
        #             start = start_time,
        #             end = end_time,
        #             personCount = request.POST['personCount'],
        #             user = user,
        #             studio = studio)
        #     object.save()
        # return redirect('booking:calendar', pk=studio.pk, year=year, month=month, day=day)

        if Schedule.objects.filter(studio=studio).exclude(Q(start__gte=end_time) | Q(end__lte=start_time)).exists():
            messages.error(request, 'すでに予約が入っています。別の日時をお選びください')
            return redirect('booking:calendar', pk=studio.pk, year=year, month=month, day=day)
        else:
            studio = studio
            personCount = request.POST['personCount']
            start_str = request.POST['start'].replace('/','-')
            end_str = request.POST['end'].replace('/','-')

            return redirect('booking:confirm', pk=studio.pk, personCount=personCount, start_str=start_str, end_str=end_str)
    else:
        return render(request, 'booking/booking.html', context)

@login_required
def Confirm(request,pk,personCount,start_str,end_str):
    studio = get_object_or_404(Studio, pk=pk)
    user = get_object_or_404(User, pk=request.user.id)
    start_str = start_str.replace('-','/')
    end_str = end_str.replace('-','/')

    context = {'studio': studio,
               'user' : user,
               'personCount' : personCount,
               'start': start_str,
               'end'  : end_str,}

    if request.method == "POST":
        object = Schedule.objects.create(
            studio = studio,
            user = user,
            personCount = personCount,
            start = datetime.datetime.strptime(start_str,'%Y/%m/%d %H:%M'),
            end = datetime.datetime.strptime(end_str,'%Y/%m/%d %H:%M'),
        )
        object.save()
        return redirect('booking:index')

    else:
        return render(request, 'booking/confirm.html', context)

class StaffStudioCalendar(StudioCalendar):
    template_name = 'booking/staffcalendar.html'

class Detail(generic.TemplateView):
    template_name = 'booking/detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        studio = get_object_or_404(Studio, pk=self.kwargs['pk'])
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        date = datetime.date(year=year, month=month, day=day)

        # 9:00~26:00、1週間分の、値がTrueなカレンダーを作る
        # "9:00"~"23:30","0:00"~"1:30"の配列
        time = []
        for i in range(9, 24):
            for j in range(0, 60, 30):
                hour = str(i).zfill(2)
                minute = str(j).zfill(2)
                time.append(hour + ":" + minute)
        for i in range(2):
            for j in range(0, 60, 30):
                hour = str(i).zfill(2)
                minute = str(j).zfill(2)
                time.append(hour + ":" + minute)
        calendar = {}
        for count in range(34):
            calendar[time[count]] = []

        start_time = datetime.datetime.combine(date, datetime.time(hour=9, minute=0, second=0))
        end_time = datetime.datetime.combine(date+datetime.timedelta(days=1), datetime.time(hour=2, minute=0, second=0))
        for schedule in Schedule.objects.filter(studio=studio).exclude(Q(start__gt=end_time) | Q(end__lt=start_time)):
            start_dt = timezone.localtime(schedule.start)
            end_dt = timezone.localtime(schedule.end)

            num_start_hour = time.index(start_dt.time().strftime("%H:%M"))
            num_end_hour = time.index(end_dt.time().strftime("%H:%M")) 

            for num in range(num_start_hour,num_end_hour):
                calendar[time[num]].append(schedule)
            # for hour in range(booking_start_hour,booking_end_hour):
            #     calendar[hour].append(schedule)

        context = { 'studio'  :studio,
                    'year'    :year,
                    'month'   :month,
                    'day'     :day,
                    'calendar':calendar}
        return context

booking/templates/booking/booking.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="col-md-3 py-4">
    <form method="POST" class="p-0">
      {% csrf_token %}
      <p>予約時間・人数を選択してください</p>
      <div class="cardgray">
        <div class="input-group date mb-3" id="ReserveStartDateTime" data-target-input="nearest">
          <label for="ReserveStartDateTime" class="pt-2 pr-2">開始：</label>
          <input type="text" class="form-control datetimepicker-input" name="start" data-target="#ReserveStartDateTime" value="{{ start }}" readonly="readonly" />
          <div class="input-group-text" data-target="#ReserveStartDateTime" data-toggle="datetimepicker">
            <i class="far fa-calendar-alt"></i>
          </div>
        </div>
        <div class="input-group date mb-3" id="ReserveEndDateTime" data-target-input="nearest">
          <label for="datetimepicker3" class="pt-2 pr-2">終了：</label>
          <input type="text" class="form-control datetimepicker-input" name="end" data-target="#ReserveEndDateTime" value="{{ end }}"/>
          <div class="input-group-text" data-target="#ReserveEndDateTime" data-toggle="datetimepicker">
            <i class="far fa-calendar-alt"></i>
          </div>
        </div>
        <div class="input-group mb-3">
          <label for="personCount" class="pt-2 pr-2">人数：</label>
          <select class="form-control" name="personCount">
            <option value="1">1人</option>
            <option value="2">2人</option>
            <option value="3">3人</option>
            <option value="4">4人</option>
            <option value="5">5人</option>
            <option value="6">6人</option>
            <option value="7">7人</option>
            <option value="8">8人</option>
            <option value="9">9人</option>
            <option value="10">10人</option>
          </select>
        </div>
        <button type="submit" class="btn btn-success">予約情報の詳細に移る</button>
      </div>
    </form>
    <script src="{% static 'booking/js/script.js' %}"></script>
  </div>
{% endblock %}

booking/templates/booking/calendar.html
{% extends 'base.html' %}

{% block content %}

    <h1 style="text-align: center;">{{ studio.name }} 予約可能時間</h1>
    <p  style="text-align: center;">{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%">
        <tr>
            <td><a href="{% url 'booking:calendar' studio.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}</th>
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}</th>
                {% else %}
                    <th>{{ day | date:"d(D)" }}</th>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'booking:calendar' studio.pk next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for time, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ time }}~
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if dt <= today %}
                            -
                        {% elif book %}
                            <a href="{% url 'booking:booking' studio.pk dt.year dt.month dt.day time %}">○</a>
                        {% else %}
                            ×
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ time }}~
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

booking/templates/booking/confirm.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
    <form method="POST" class="p-4 confirm">
        {% csrf_token %}
        <h2>予約情報確認</h2>
        <p>内容が正しければ予約確定ボタンを押してください</p>
        <div class="cardgray">
            <div>
                <label class="pt-2 pr-2">予約者氏名：{{ user.last_name }} {{ user.first_name }}</label>
            </div>
            <div>
                <label class="pt-2 pr-2">スタジオ：{{ studio.name }}</label>
            </div>
            <div>
                <label class="pt-2 pr-2">予約開始時刻：{{ start }}</label>
            </div>
            <div>
                <label class="pt-2 pr-2">予約終了時刻：{{ end }}</label>
            </div>
            <div>
                <label class="pt-2 pr-2">利用人数：{{ personCount }}</label>
            </div>
            <button type="submit" class="btn btn-success">予約確定</button>
        </div>
    </form>
{% endblock %}

booking/templates/booking/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="text-align: center;">{{ studio.name }}</h1>
    <h1 style="text-align: center;">{{ year }}年{{ month }}月{{ day }}日</h1>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" >
        <tr>
            <td>時間帯</td>
            <td>予約</td>
            <td>氏名</td>
            <td>電話番号</td>
            <td>人数</td>
        </tr>
        {% for time, schedules in calendar.items %}
            <tr>
                <td>{{ time }}</td>
                {% if schedules %}
                    {% for schedule in schedules%}
                        <td>有り</td>
                        <td>{{ schedule.user.last_name }} {{ schedule.user.first_name }}</td>
                        <td>{{ schedule.user.phone_number }}</td>
                        <td>{{ schedule.personCount }}</td>
                    {% endfor %}
                {% else %}
                    <td>無し</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

{% endblock %}

booking/templates/booking/index.html
{% extends "base.html" %}

{% block content %}

{% if user.is_staff %}
<h1>管理者用</h1>
{% for studio in object_list %}
<li><a href="{% url 'booking:staffcalendar' studio.pk %}">{{ studio.name }}</a></li>    
{% empty %}
<li>まだスタジオがありません</li>        
{% endfor %}

{% else %}
{% for studio in object_list %}
<li><a href="{% url 'booking:calendar' studio.pk %}">{{ studio.name }}</a></li>    
{% empty %}
<li>まだスタジオがありません</li>        
{% endfor %}
{% endif %}

{% endblock %}

booking/templates/booking/staffcalendar.html
{% extends "base.html" %}

{% block content %}

    <h1>管理者用</h1>
    <h1 style="text-align: center;">{{ studio.name }}</h1>
    <p  style="text-align: center;">{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%">
        <tr>
            <td style="vertical-align:middle;"><a href="{% url 'booking:staffcalendar' studio.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}
                {% else %}
                    <th>{{ day | date:"d(D)" }}
                {% endif %}
                <br><a href="{% url 'booking:detail' studio.pk  day.year day.month day.day %}">詳細</a></th>
            {% endfor %}
            <td style="vertical-align:middle;"><a href="{% url 'booking:staffcalendar' studio.pk next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for time, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ time }}~
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if book %}
                            ○
                        {% else %}
                            ×
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ time }}~
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}